---
title: "HomeworkAPI"
author: "Yue Shang"
date: "4/6/2021"
output: word_document
---

```{r}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
# 1)  
census_api_key("242c6a1c9b843410c00133a330a9bb73463b6e80")
install=TRUE
```

```{r}
# 2)  
## a)  
data1 <- load_variables(2015, "acs5", cache = TRUE)
view(data1)
```

```{r}
data2<- get_acs(geography = "county", 
              variables = c(mediancome = "B01001A_011"), 
              state = "California",
              year = 2015)

data2

## b)  
data2 %>% 
  filter(estimate>30000) %>% 
  arrange(desc(estimate))->data3
data3
## c)  
data3 %>% 
  filter(estimate==51644 , moe==667)->data4
data4

## d)  
ggplot(data3,aes(x=estimate),horizontal=TRUE)+
  geom_boxplot(aes(fill="red"))

## e)  
data3 %>%
  mutate(NAME = gsub(" County, California", "", NAME)) %>%
  ggplot(aes(x = estimate, y = reorder(NAME, estimate))) +
  geom_errorbarh(aes(xmin = estimate - moe, xmax = estimate + moe)) +
  geom_point(color = "blue", size = 2) +
  labs(title = "Median Income for White Males by County",
       subtitle = "2014-2018 American Community Survey",
       y = "",
       x = "ACS estimate (bars represent margin of error)")

```

